name: Publish to NuGet

on:
  push:
    branches:
      - master # Default release branch

jobs:
  publish:
    name: Build, Pack & Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore LLMinster.Interfaces.sln

      - name: Get version from LLMinster.Interfaces.csproj
        id: get_version
        run: |
          version=$(grep '<Version>' LLMinster.Interfaces.csproj | sed 's/.*<Version>\(.*\)<\/Version>.*/\1/')
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Build
        run: dotnet build LLMinster.Interfaces.sln --no-restore --configuration Release

      - name: Pack
        run: dotnet pack LLMinster.Interfaces.csproj --no-build --configuration Release --output ./artifacts /p:PackageVersion=${{ env.VERSION }}

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./artifacts/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
